- name: ensure mariadb is installed
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: latest
    update_cache: yes

- name: Crear base de datos
  community.mysql.mysql_db:
    name: "{{ guestbook_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Crear usuario y otorgar privilegios
  community.mysql.mysql_user:
    name: "{{ guestbook_db_user }}"
    password: "{{ guestbook_db_password }}"
    host: "%"
    priv: "{{ guestbook_db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Copiar esquema SQL al servidor MariaDB
  ansible.builtin.copy:
    src: schema.sql
    dest: /tmp/schema.sql

- name: Comprobar si la tabla 'messages' existe
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "SHOW TABLES FROM {{ guestbook_db_name }} LIKE 'messages';"
  register: table_check

- name: Importar esquema SQL (solo si la tabla no existe)
  community.mysql.mysql_db:
    name: "{{ guestbook_db_name }}"
    state: import
    target: /tmp/schema.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: table_check.query_result[0] | length == 0



- name: Configurar MariaDB para escuchar en todas las interfaces
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present
  notify: restart mariadb

### CREAR BASE DE DATOS DE WORDPRESS Y USUARIO

- name: Crear base de datos de WordPress
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Crear usuario de WordPress
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    host: "%"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Copiar dump SQL de WordPress
  copy:
    src: wordpress.sql
    dest: /tmp/wordpress.sql

- name: Importar base de datos WordPress
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: import
    target: /tmp/wordpress.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock

### CREAR BASE DE DATOS DE LA APP PHP BIBLIOTECA

- name: Crear base de datos Biblioteca
  community.mysql.mysql_db:
    name: "{{ biblioteca_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Crear usuario de Biblioteca
  community.mysql.mysql_user:
    name: "{{ biblioteca_db_user }}"
    password: "{{ biblioteca_db_password }}"
    host: "%"
    priv: "{{ biblioteca_db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Copiar SQL dump de Biblioteca
  copy:
    src: biblioteca.sql
    dest: /tmp/biblioteca.sql

- name: Importar base de datos Biblioteca
  community.mysql.mysql_db:
    name: "{{ biblioteca_db_name }}"
    state: import
    target: /tmp/biblioteca.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock