#cloud-config
hostname: mariadb
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILtxXRSWN/7JFi5fXkm/pmy5/jATSdx+P/N3959ow/tY jfalcon@jfalcon
chpasswd:
  expire: False
  users:
    - name: ubuntu
      password: asdasd
      type: text
